name: build
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: install packages
        run: npm install
      - name: build production
        run: npm run build